### ISSUE TITLE
It seems a CORESVG issue - Here after installation 

### ISSUE THREAD

**Issue by aarkkappler** [miraclx/freyr-gui#2]
Hi,

he situation on Mac (Big Sur OS)

There is no actionable buttons, nothings works

![image](https://user-images.githubusercontent.com/9117901/126153592-af7e2861-cea1-46bf-b124-3b5cccd3d963.png)

Thank you

**Comment by miraclx** [comment]
No, that's exactly what it's meant to do. As stated on the readme, it's just a mockup, there's no logic.
